# 后台管理数据库
mysql_settings:
  MYSQL_DB: 'dy_gather'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'xxxxxx'
  MYSQL_HOST: 'xxxxx'
  MYSQL_PORT: 'xxxxxx'

# 多程序后台接口
server_settings:
#  抖音抓取
  tk_catch:
    url: 'xxxxxx'
    MYSQL_DB: 'dy_gather'


API_KEY:
  # 高德地图api
  AMAP_KEY : 'xxx'
# google gmini api key
  GeminiKey: 'AIzaSyCp711bYGhS-pf2E51fAwmX1YXHXZcSRkk'