mysql_settings:
  MYSQL_DB: 'dy_gather'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '123456'
  MYSQL_HOST: '127.0.0.1'
  MYSQL_PORT: '3306'


server_settings:
    url: 'http:scccy6.cn:5444'
    MYSQL_DB: 'dy_gather'
