mysql_settings:
  MYSQL_DB: 'dy_gather'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '*****'
  MYSQL_HOST: '192.168.31.85'
  MYSQL_PORT: '5306'


server_settings:
    url: 'http://192.168.31.85:5000/'
    MYSQL_DB: 'django_web'
